version: '3'

networks:
  app-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    networks:
      - app-network
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/coollider/coollider.crt:/etc/ssl/coollider/coollider.crt
      - /etc/ssl/coollider/coollider.key:/etc/ssl/coollider/coollider.key
      - /var/www/html:/var/www/html
    networks:
      - app-network
    links:
      - web:web
